Feature/password encryption
YCP-Swarm-Robotics-Capstone-2020-2021/swarm-website-frontend pull request #30
Opened 2020-09-15 01:57 UTC by Rithonn

This will focus on getting the signup and login page working for the website.

2020-09-23 14:35 UTC, Rithonn commented
There is a good stopping point for now. The next step is to implement this on the backend.

2020-09-25 13:43 UTC, Rithonn commented
@Walrussuit101 @cbrandt6 Would you guys be able to review this so we can get this merged then?

2020-09-25 13:49 UTC, cbrandt6 approved these changes
Good Stuff

2020-09-25 13:54 UTC, Walrussuit101 requested changes
Awesome work

2020-09-25 13:54 UTC, Walrussuit101 commented on src/components/LogIn/LogIn.tsx
> +    }
don't wanna use any

2020-09-25 13:54 UTC, Walrussuit101 commented on src/components/SignUp/SignUp.tsx
> +    }
any, doesn't even look like it needs a constructor since there isn't a props interface

2020-09-25 13:54 UTC, Walrussuit101 commented on src/App.tsx
> +                <Route path='/signUp' component={SignUp}/>
do we wanna use camel case for the routes? just curious because 'personalpage' doesn't, just something we can quickly decide in discord

2020-09-27 15:47 UTC, Rithonn commented
@Walrussuit101 Changes have been completed

2020-09-27 15:55 UTC, Walrussuit101 approved these changes

2020-09-27 20:00 UTC, merged